### ISSUE TITLE
Local configuration is not used because pulling from REPO

### ISSUE THREAD

**Issue by justintime4tea** [htdvisser/taiga-docker#11]
I may be wrong but it appears none of the local changes to files are respected/used during the docker-compose "up" process?

I say this because in your Dockerfiles you do not copy local files you instead pull from github each time. Is this the case? Are local changes not being copied into the containers and instead the same Github-repo files used everytime? Then what's the point of local env settings? (please let me know if I'm wrong, just going off dockerfile and observation) Should I fork your repo, commit my changes to my fork, replace your repo in Dockerfiles with my fork and THEN my env-conf will be pulled during container creation?

Maybe I'm wrong but I cannot for the LIFE of me seem to change the DB name and it keeps failing looking for a DB that does not exist. The file "dockerenv.py" never gets ANY of the env-vars I set in either the docker-compose.yml(taiga.yml) or the individual Dockerfiles within taiga-back. 

I'm not new to working with pre-built images (can build my own fine as well) I'm simply trying to weed through all of the different BASH scripts and things your team has built to "auto-magic" setup these containers and cannot figure out to "force" my env-vars to be used.

I'm not trying to bash anyone (no pun intended) I am just trying to provide feedback and figure out where the heck I am going wrong. Sometimes Dockerfiles and pre-built images can be a rat maze >_<

If anyone has even just 10 minutes to help me hash this out it would be much appreciated. I am a seasoned enterprise developer so it's not like helping some uber newb ;) Apologies if this issue is isolated to my system and I am out-of-line. I will gladly remove issue if this is the case.

**Comment by htdvisser** [comment]
There's currently an issue with the database environment (see #10), which might be the reason you're having a problem here.

As for the container configuration: When I created these images, my idea was that containers (once created) are sort of immutable. All configuration is passed to the container once on start. Then the `configure` script puts the environment vars that are defined in the `taiga.yml` file, into the `dockerenv.py` file and it should 'just work'. 

I can imagine that in many situations you might want to add more configuration options. In that case, you should indeed fork and add your specific configuration yourself. If you think it might be useful for others as well, feel free to send a pull request.

I hope this (partly) answers your questions. For now I'll close this issue, but I'll keep the discussion open.
