### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by htdvisser** [htdvisser/taiga-docker#14]
I'm not working with Taiga anymore, and therefore looking for maintainers for this project. Please comment on this issue if you're interested.

**Comment by beevelop** [comment]
I'm currently maintaining an up-to-date version of [Taiga's backend](https://github.com/beevelop/docker-taiga-back/tree/alpine) and [Taiga's frontend](https://github.com/beevelop/docker-taiga-front/tree/alpine) which where originally based on your work. I made a few adaptions (like explicitly defining the version, extending the available configurations,...) and just recently got an Alpine-based version running (to save those precious bits).
So yeah, I would be interested.

**Comment by htdvisser** [comment]
Thanks for your comment, @beevelop! I looked at your repositories and I think they look good (although I'm not the biggest fan of random emojis in commit messages). My only concern is that your image is not completely compatible with mine, so it will not be possible to just switch.

My proposal is as follows: I add you as a collaborator to this project and you agree to support minor version updates (security updates) for a while. In the meantime the documentation is updated to point users to your project and to provide a migration guide. When the majority of the users has moved to your project, or when Taiga gets a major update, this project will no longer be updated for new Taiga versions.

Let me know what you think!

**Comment by lenybernard** [comment]
Hello, I'm also volunteer !

**Comment by htdvisser** [comment]
Thanks @lenybernard and @beevelop for volunteering. I added both of you as collaborators to this repository!
