### ISSUE TITLE
open() "/usr/local/taiga/taiga-front-dist/dist/js/conf.json" failed (2: No such file or directory)

### ISSUE THREAD

**Issue by JadianZheng** [htdvisser/taiga-docker#19]
It's the bad time when I change the docker default setting to new a new machine. 
And I found it have some problem to usage it and I remove the machine at time. 
Then I run the taiga in default machine, and it just jump to the error page that wirte the words - `Something happened and our Oompa Loompas are working on it.`

> And I got the message `open() "/usr/local/taiga/taiga-front-dist/dist/js/conf.json" failed (2: No such file or directory)` int taigafront's log.
### More like this:

> 2016/05/22 15:48:51 [error] 12#0: *1 open() "/usr/local/taiga/taiga-front-dist/dist/js/conf.json" failed (2: No such file or directory), client: 192.168.99.1, server: localhost, request: "GET /js/conf.json HTTP/1.1", host: "192.168.99.100", referrer: "http://192.168.99.100/"
> 
> 192.168.99.1 - - [22/May/2016:15:48:51 +0000] "GET /js/conf.json HTTP/1.1" 404 191 "http://192.168.99.100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36" "-"
> 
> 2016/05/22 15:48:58 [error] 12#0: *1 open() "/usr/local/taiga/taiga-front-dist/dist/js/conf.json" failed (2: No such file or directory), client: 192.168.99.1, server: localhost, request: "GET /js/conf.json HTTP/1.1", host: "192.168.99.100", referrer: "http://192.168.99.100/"
> 
> 192.168.99.1 - - [22/May/2016:15:48:58 +0000] "GET /js/conf.json HTTP/1.1" 404 191 "http://192.168.99.100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36" "-"
> 
> 192.168.99.1 - - [22/May/2016:15:50:33 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Kitematic/0.10.2 Chrome/45.0.2454.85 Electron/0.35.4 Safari/537.36" "-"
> 
> 192.168.99.1 - - [22/May/2016:15:50:33 +0000] "GET /conf.json HTTP/1.1" 200 264 "http://192.168.99.100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Kitematic/0.10.2 Chrome/45.0.2454.85 Electron/0.35.4 Safari/537.36" "-"
> 
> 192.168.99.1 - - [22/May/2016:15:50:35 +0000] "GET /v-1461931321319/locales/taiga/locale-en.json HTTP/1.1" 304 0 "http://192.168.99.100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Kitematic/0.10.2 Chrome/45.0.2454.85 Electron/0.35.4 Safari/537.36" "-"`

**Comment by htdvisser** [comment]
The `taiga-front-dist/dist/js/conf.json` moved to `taiga-front-dist/dist/conf.json` (see [taiga upgrade guide](https://taigaio.github.io/taiga-doc/dist/upgrades.html#_1_9_0_1_9_1)). Is it possible that you're using an old volume mapping?

**Comment by JadianZheng** [comment]
@htdvisser I uesd kitematic to run the terminal, and I found all things was done under what the upgrade doc writed.

I also try to reinstall the docker and your taiga-docker, and this issue show again...
Maybe I did some wrong with the uninstall step?
