### ISSUE TITLE
Env var POSTGRES_PORT duplicate declaration

### ISSUE THREAD

**Issue by nsymms** [htdvisser/taiga-docker#27]
When using docker-compose, if your database container is named "postgres," compose will auto-create an environment variable called POSTGRES_PORT that looks like "tcp://172.x.y.z:5432". That is, unless the variable already has a value.

So if you don't specifically declare POSTGRES_PORT in docker-compose or elsewhere, the value above will be filled in for POSTGRES_PORT and taiga-back will try to use it as the port to connect to. It fails in the "waiting for postgres" stage within the start script, because nc chokes.

As a workaround, I simply declare POSTGRES_HOST=postgres and POSTGRES_PORT=5432 within docker-compose.yml. This works well if your database is linked as "postgres".

**Comment by beevelop** [comment]
@nsymms `taiga.yml` has been updated through #28 to provide proper / working default values for `POSTGRES_HOST` and `POSTGRES_POST`
