### ISSUE TITLE
docker-compose up failed

### ISSUE THREAD

**Issue by jedi-jiang** [htdvisser/taiga-docker#29]
Running docker-compose up results in this error:

taigaback_1 | tcp://172.17.0.3:5432: forward host lookup failed: Unknown host

I believe I followed all the instructions.

I could connect to the postgresql db in cntainer taigaback_1 through the psql.

**Comment by chinaares** [comment]
I had met this error too,any one give some help?

**Comment by filhocf** [comment]
You need to set two variables: POSTGRES_HOST and POSTGRES_PORT

Can be in the docker-compose.yml or with option -e.

**Comment by beevelop** [comment]
Have a look at #28 (merged just now) and the new `taiga.yml` file.
You might need to set the environment variables explicitly for `taigaback` to circumvent naming conflicts (ENV <> container name):
```yml
environment:
  [...]
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
```
