### ISSUE TITLE
Uploads don't seem to work..

### ISSUE THREAD

**Issue by gabeos** [htdvisser/taiga-docker#3]
Hi there, thanks so much for dockerizing taiga.io. It's super useful for a bunch of my projects that need a quick collaboration tool. 

I've been having a problem with file attachments uploads though. While uploads seem to proceed, and I can add the name and save them there, they disappear upon reloading the page. This happens with uploads attached to both wiki pages and kanban stories.

Any thoughts?

**Comment by htdvisser** [comment]
Hi @gabeos, I just installed the images on a clean machine (using the docker-compose config) and I do not have any issues with uploaded files. You could try to check the permissions of the `/usr/local/taiga/media` directory in your `taiga-back` container.

**Comment by gabeos** [comment]
Yup, figured it was probably a permissions thing. 

Steps I took to fix: 

in taiga_back: 

`chown -R taiga /usr/local/taiga` 

in taiga_front 

`chown -R :nginx /usr/local/taiga` 

Also, here's my fig.yml/docker-compose that presumably brought on the
issue somehow: 

---

data:
 image: python:3.4
 entrypoint: "/bin/echo"
 command: "taiga data container"
 volumes:
- /var/lib/postgresql/data
- /usr/local/taiga/media
- /usr/local/taiga/static
- /usr/local/taiga/logs
  db:
  image: postgres
  environment:
- POSTGRES_USER=taiga
- POSTGRES_PASSWORD=<redacted>
  volumes_from:
- data
  taigaback:
  image: htdvisser/taiga-back:stable
  hostname: planning.noise.yoga
  environment:
  SECRET_KEY: <redacted>
  EMAIL_USE_TLS: True
  EMAIL_HOST: <redacted>
  EMAIL_PORT: 587
  EMAIL_HOST_USER: <redacted>
  EMAIL_HOST_PASSWORD: <redacted>
  DEFAULT_FROM_EMAIL: <redacted>
  links:
- db:postgres
  volumes_from:
- data
  taigafront:
  image: htdvisser/taiga-front-dist:stable
  hostname: <redacted>
  links:
- taigaback
  volumes_from:
- data
  environment:
  VIRTUAL_HOST: <redacted> // For jwilder's nginx reverse proxy
  PUBLIC_REGISTER_ENABLED: "true" 

---

IIRC, I started it with PUBLIC_REGISTER_ENABLED='true', and then changed
it manually to false in config after initial registration. 

Thanks! 

On 2015-05-10 03:45, Hylke Visser wrote: 

> Hi @gabeos [1], I've installed the images on a clean machine (using the docker-compose config) and I do not have any issues with uploaded files. You could try to check the permissions of the /usr/local/taiga/media directory in your taiga-back container. 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [2].

## Links:

[1] https://github.com/gabeos
[2]
https://github.com/htdvisser/taiga-docker/issues/3#issuecomment-100620697

**Comment by htdvisser** [comment]
Hi @gabeos, 

I think changing the permissions of the entire `/usr/local/taiga` is a little bit too much. Access on `/usr/local/taiga/media` should be enough.

**Comment by michael-schaefer-eu** [comment]
Hi,

I had the same problem with upload and granting access only on `/usr/local/taiga/media` is not enough, the steps from gabeos where necessary on my server.

PS: Thanks for this great container :)
