### ISSUE TITLE
502 (Bad Gateway) on api/v1/auth/register

### ISSUE THREAD

**Issue by bastien-g** [htdvisser/taiga-docker#4]
Hi,

First, thank's for your work. I installed taiga using your docker-compose and I am unable to create a new user. I get _502 (Bad Gateway)_ on _api/v1/auth/register_.
I found this issue that may be related [taigaio/taiga-back/#244](https://github.com/taigaio/taiga-back/issues/244).
So I looked at my _/usr/local/taiga/taiga-back/settings/local.py_ as mentioned in the [taiga documentation](https://github.com/taigaio/taiga-doc/blob/master/setup-production.adoc) and found there is nothing in it about email configuration whereas I set all EMAIL_  environments variables in docker-compose.yml
Is it an error or did I miss something ?

**Comment by htdvisser** [comment]
Hi @bastien-g,

All these settings are configured when your container starts (see the [configure script](https://github.com/htdvisser/taiga-docker/blob/stable/taiga-back/configure#L51)).
In my experience, this error usually means that either the server hasn't started yet, or you that forgot to [initialize the database](https://github.com/htdvisser/taiga-docker/tree/stable/taiga-back#database-initialization).

**Comment by bastien-g** [comment]
Hi @htdvisser,
Thanks for your answer.
I am sure the server is started and database initialized cause I am able to log in with the admin account.

Ok for the email configuration I found that my _dockerenv.py_ file is correctly initialized with docker env vars.

I re-run the installation from scratch with docker-compose and noticed I get `Installed 0 object(s) from 0 fixture(s)` when trying to initialize the database with `python manage.py loaddata initial_role`. 

Is it normal ?

**Comment by htdvisser** [comment]
I get the same message, so I guess it is normal. Maybe check the server logs in (`/usr/local/taiga/logs`) to see what's going wrong when you get the 502.

**Comment by bastien-g** [comment]
There is nothing in `/usr/local/taiga/logs` about that 502 error, only css errors and `Raven is not configured (logging is disabled)`

I will try to install with your new build. btw the docker-compose.yml on DockerHub is not correctly formatted since the update

**Comment by htdvisser** [comment]
Fixed the yml on DockerHub, thanks.
