### ISSUE TITLE
Docker images up to date? 

### ISSUE THREAD

**Issue by kyleschlosser** [htdvisser/taiga-docker#6]
I was wondering if your Docker images are up to date? I do not see the SSL configuration taking effect. 

I ran: 
docker pull htdvisser/taiga-front-dist:stable
docker run htdvisser/taiga-front-dist:stable cat /usr/local/taiga/configure

The script I see does not include the ssl configuration like I see here: 
https://github.com/htdvisser/taiga-docker/blob/stable/taiga-front-dist/configure

**Comment by htdvisser** [comment]
I removed the tag `stable` from Docker Hub some time ago. I now aliased it to `latest` (which is the taiga `stable` branch). Images should be built within a few minutes.
