### ISSUE TITLE
Can't choose kanban/scrum when creating new project

### ISSUE THREAD

**Issue by maerten** [htdvisser/taiga-docker#7]
It appears the following commands need to be executed manually from inside the container, after starting up with docker-compose:

```
cd /usr/local/taiga/taiga-back
python manage.py migrate --noinput
python manage.py loaddata initial_user
python manage.py loaddata initial_project_templates
python manage.py loaddata initial_role
python manage.py collectstatic --noinput
```

**Comment by htdvisser** [comment]
That is correct, the first time you install Taiga, you have to initialize your database, see the [README](https://hub.docker.com/r/htdvisser/taiga-back/).

**Comment by maerten** [comment]
Ah I haven't seen that page before. Perhaps it would be an idea to point people to this readme at https://github.com/htdvisser/taiga-docker/
Other than this issue I had your images work great, thanks!
